services:
  app:
    container_name: home-library-service
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
    working_dir: /app
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: vilkasts/nodejs2024q3-service-app:latest
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    restart: always
    networks:
      - home-library-service-network
    volumes:
      - app_logs:/var/log/app

  db:
    container_name: home-library-service-db
#    build:
#      context: ./prisma
#      dockerfile: Dockerfile
    image: vilkasts/nodejs2024q3-service-db:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    networks:
      - home-library-service-network
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  app_logs:
  db_data:

networks:
  home-library-service-network:
    driver: bridge