services:
  app:
    container_name: home-library-service
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${PORT}:${PORT}
    networks:
      - home-library-service-network
    working_dir: /app
    restart: always
    volumes:
      - app_logs:/var/log/app

  db:
    build:
      context: ./prisma
      dockerfile: Dockerfile
    container_name: home-library-service-db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - home-library-service-network

volumes:
  app_logs:
  db_data:

networks:
  home-library-service-network:
    driver: bridge